version: '2'

services:
  database:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=DB
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
      
  backend:
    image: nahomiaparicio/so1_backend1
    privileged: true
    pid: host
    container_name: backend_container
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - DB_NAME=DB
    ports:
      - '8000:8000'
    volumes:
     - type: bind
       source: /proc
       target: /proc     
    restart: always
    depends_on:
      - database
    links:
      - database
    
      
  frontend:
    image: nahomiaparicio/frontendf:2.2.0
    container_name: front_container
    ports:
      - '80:80'
    restart: always
    depends_on:
      - backend
    links:
      - backend      
  
volumes:
  mongo-data:
    external: false




