apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: so1jun2024
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: nahomiaparicio/consumer-kafka:2.1.0
        resources:
          limits:
            cpu: "0.5"
            memory: "1Gi"
          requests:
            cpu: "0.3"
            memory: "700Mi"
